
package br.com.magabrew.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListarCervejasService", targetNamespace = "http://service.magabrew.com.br/", wsdlLocation = "http://localhost:8180/Produtos?wsdl")
public class ListarCervejasService
    extends Service
{

    private final static URL LISTARCERVEJASSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTARCERVEJASSERVICE_EXCEPTION;
    private final static QName LISTARCERVEJASSERVICE_QNAME = new QName("http://service.magabrew.com.br/", "ListarCervejasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8180/Produtos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTARCERVEJASSERVICE_WSDL_LOCATION = url;
        LISTARCERVEJASSERVICE_EXCEPTION = e;
    }

    public ListarCervejasService() {
        super(__getWsdlLocation(), LISTARCERVEJASSERVICE_QNAME);
    }

    public ListarCervejasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTARCERVEJASSERVICE_QNAME, features);
    }

    public ListarCervejasService(URL wsdlLocation) {
        super(wsdlLocation, LISTARCERVEJASSERVICE_QNAME);
    }

    public ListarCervejasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTARCERVEJASSERVICE_QNAME, features);
    }

    public ListarCervejasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListarCervejasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListarCervejas
     */
    @WebEndpoint(name = "ListarCervejasPort")
    public ListarCervejas getListarCervejasPort() {
        return super.getPort(new QName("http://service.magabrew.com.br/", "ListarCervejasPort"), ListarCervejas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListarCervejas
     */
    @WebEndpoint(name = "ListarCervejasPort")
    public ListarCervejas getListarCervejasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.magabrew.com.br/", "ListarCervejasPort"), ListarCervejas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTARCERVEJASSERVICE_EXCEPTION!= null) {
            throw LISTARCERVEJASSERVICE_EXCEPTION;
        }
        return LISTARCERVEJASSERVICE_WSDL_LOCATION;
    }

}
