
package br.com.magabrew.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListarCervejas", targetNamespace = "http://service.magabrew.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListarCervejas {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.magabrew.service.Produto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCervejas", targetNamespace = "http://service.magabrew.com.br/", className = "br.com.magabrew.service.ListarCervejas_Type")
    @ResponseWrapper(localName = "listarCervejasResponse", targetNamespace = "http://service.magabrew.com.br/", className = "br.com.magabrew.service.ListarCervejasResponse")
    @Action(input = "http://service.magabrew.com.br/ListarCervejas/listarCervejasRequest", output = "http://service.magabrew.com.br/ListarCervejas/listarCervejasResponse")
    public List<Produto> listarCervejas();

}
